export enum ActionsMovements {
    SALIDA_COTIZACION = "SALIDA_COTIZACION",
    ENTRADA_COTIZACION = "ENTRADA_COTIZACION",
    SALIDA_PRESTAMO = "SALIDA_PRESTAMO",
    ENTRADA_PRESTAMO = "ENTRADA_PRESTAMO",
    SALIDA_GARANTIA = "SALIDA_GARANTIA",
    ENTRADA_GARANTIA = "ENTRADA_GARANTIA",
    TRASLADO = "TRASLADO",
    INGRESO_BODEGA = "INGRESO_BODEGA",
    INGRESO_TALLER = "INGRESO_TALLER",
  }
  